name: Discord Notification

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1387674208921849906/WlfFXkevX5v0cvmjXzmuryB9g1-itj-tZf2EsZLj9Ynh_yhpQFkoEkAqGR-xWmgVQTIb
        run: |
          USERNAME="${{ github.actor }}"
          BRANCH_NAME="${{ github.ref_name }}"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ New push by **$USERNAME** to branch **$BRANCH_NAME**!\"}" \
            $DISCORD_WEBHOOK
